lm:
  provider: "anthropic"
  model_mappings:
    haiku: "claude-3-5-haiku-20241022"

mcp:
  servers:
    shopify:
      command: "npx"
      args:
        - "shopify-mcp"
        - "--accessToken"
        - "${SHOPIFY_ACCESS_TOKEN}"
        - "--domain"
        - "${SHOPIFY_DOMAIN}"
        - "--maxResults"
        - "8"