# This configures how Fast-Agent works
llm:
  provider: "anthropic"
  model_mappings:
    sonnet: "claude-3-5-sonnet-20241022"
    haiku: "claude-3-5-haiku-20241022"

mcp:
  servers:
    shopify:
      #Using local Docker server for now
      command: "docker"
      args:
        - "run"
        - "-i"
        - "--rm"
        - "-e"
        - "SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}"
        - "-e"
        - "MYSHOPIFY_DOMAIN=${MYSHOPIFY_DOMAIN}"
        - "ghcr.io/metorial/mcp-container--geli2001--shopify-mcp--shopify-mcp"